language: php

env:
  - SH=bash

sudo: false

git:
  depth: 2

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - composer test